name: e_shop
description: E-Shop

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.3 # helps to use SVG in app
  provider: ^4.3.3 # for State management
  shared_preferences: ^0.5.12+4 # for saving setting to local storage
  theme_provider: ^0.4.0+1 # for using multiple themes like dark/light
  http: ^0.13.0 # for converting data to jason
  json_annotation: ^3.1.1 # for annotation of data for jason
  local_auth: ^1.1.0 # authentication sensors such as Fingerprint Reader and Touch ID ^1.1.0
  uuid: ^2.2.2 # RFC4122 (v1, v4, v5) UUID Generator and Parser
  modal_progress_hud: ^0.1.3 # loading progress spinner
  sprintf: ^5.0.0 # used for localization
  url_launcher: ^5.7.10 # for launching phone call and mailto
  font_awesome_flutter: 8.4.0 # icons
  date_time_picker: ^2.0.0
  intl: ^0.17.0 # ^0.17.0 for local_auth ^0.16.1
  image_picker: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Italic.ttf
          style: italic
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/muli/Muli-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/muli/Muli-Semi-BoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
        - asset: assets/fonts/muli/Muli-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/muli/Muli-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/muli/Muli-ExtraLightItalic.ttf
          weight: 100
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
